CREATE TABLE "Categorias" (
  "id_categoria" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar UNIQUE NOT NULL,
  "descripcion" text
);

CREATE TABLE "Marcas" (
  "id_marca" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar UNIQUE NOT NULL
);

CREATE TABLE "Proveedores" (
  "id_proveedor" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "razon_social" varchar NOT NULL,
  "cuit" varchar UNIQUE NOT NULL,
  "telefono" varchar,
  "email" varchar
);

CREATE TABLE "Sucursales" (
  "id_sucursal" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar NOT NULL,
  "direccion" varchar,
  "ciudad" varchar
);

CREATE TABLE "Empleados" (
  "id_empleado" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "documento" varchar UNIQUE NOT NULL,
  "nombre" varchar NOT NULL,
  "apellido" varchar NOT NULL,
  "perfil_acceso" varchar
);

CREATE TABLE "Productos" (
  "id_producto" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar NOT NULL,
  "descripcion" text,
  "precio_venta_actual" decimal,
  "id_marca" int NOT NULL,
  "id_categoria" int NOT NULL
);

CREATE TABLE "Talles" (
  "id_talle" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nomenclatura" varchar UNIQUE NOT NULL
);

CREATE TABLE "Colores" (
  "id_color" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre_color" varchar UNIQUE NOT NULL
);

CREATE TABLE "Producto_Variante" (
  "id_variante" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "codigo_barras" varchar UNIQUE NOT NULL,
  "id_producto" int NOT NULL,
  "id_talle" int NOT NULL,
  "id_color" int NOT NULL
);

CREATE TABLE "Inventario" (
  "id_sucursal" int,
  "id_variante" int,
  "cantidad_disponible" int,
  PRIMARY KEY ("id_sucursal", "id_variante")
);

CREATE TABLE "Movimientos" (
  "id_movimiento" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fecha_hora" timestamp NOT NULL,
  "tipo_movimiento" varchar,
  "observaciones" text,
  "id_sucursal_origen" int,
  "id_sucursal_destino" int,
  "id_empleado" int NOT NULL
);

CREATE TABLE "Detalle_Movimientos" (
  "id_detalle" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cantidad" int NOT NULL,
  "precio_unitario" decimal NOT NULL,
  "id_movimiento" int NOT NULL,
  "id_variante" int NOT NULL
);

COMMENT ON COLUMN "Empleados"."perfil_acceso" IS 'CHECK (perfil_acceso IN (''Administrador'', ''Operativo'', ''Consulta''))';

COMMENT ON COLUMN "Productos"."precio_venta_actual" IS 'CHECK (precio_venta_actual > 0)';

COMMENT ON COLUMN "Inventario"."cantidad_disponible" IS 'CHECK (cantidad_disponible >= 0)';

COMMENT ON COLUMN "Movimientos"."tipo_movimiento" IS 'CHECK (tipo_movimiento IN (''Entrada'', ''Salida'', ''Traslado''))';

COMMENT ON COLUMN "Detalle_Movimientos"."cantidad" IS 'CHECK (cantidad > 0)';

COMMENT ON COLUMN "Detalle_Movimientos"."precio_unitario" IS 'CHECK (precio_unitario >= 0)';

ALTER TABLE "Productos" ADD FOREIGN KEY ("id_marca") REFERENCES "Marcas" ("id_marca") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Productos" ADD FOREIGN KEY ("id_categoria") REFERENCES "Categorias" ("id_categoria") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Producto_Variante" ADD FOREIGN KEY ("id_producto") REFERENCES "Productos" ("id_producto") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Producto_Variante" ADD FOREIGN KEY ("id_talle") REFERENCES "Talles" ("id_talle") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Producto_Variante" ADD FOREIGN KEY ("id_color") REFERENCES "Colores" ("id_color") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Inventario" ADD FOREIGN KEY ("id_sucursal") REFERENCES "Sucursales" ("id_sucursal") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Inventario" ADD FOREIGN KEY ("id_variante") REFERENCES "Producto_Variante" ("id_variante") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Movimientos" ADD FOREIGN KEY ("id_sucursal_origen") REFERENCES "Sucursales" ("id_sucursal") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Movimientos" ADD FOREIGN KEY ("id_sucursal_destino") REFERENCES "Sucursales" ("id_sucursal") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Movimientos" ADD FOREIGN KEY ("id_empleado") REFERENCES "Empleados" ("id_empleado") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Detalle_Movimientos" ADD FOREIGN KEY ("id_movimiento") REFERENCES "Movimientos" ("id_movimiento") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Detalle_Movimientos" ADD FOREIGN KEY ("id_variante") REFERENCES "Producto_Variante" ("id_variante") DEFERRABLE INITIALLY IMMEDIATE;
